const canvas=document.querySelector('#canvas');
const ctx=canvas.getContext('2d');
const $=selector=>document.querySelector(selector);
const ui={file:$('#fileInput'),demo:$('#demoBtn'),clear:$('#clearBtn'),list:$('#layerList'),name:$('#nameInput'),category:$('#categoryInput'),scale:$('#scaleInput'),rotation:$('#rotationInput'),opacity:$('#opacityInput'),blur:$('#blurInput'),depth:$('#depthInput'),visible:$('#visibleInput'),locked:$('#lockedInput'),back:$('#backBtn'),front:$('#frontBtn'),delete:$('#deleteBtn'),png:$('#pngBtn'),json:$('#jsonBtn'),prompt:$('#promptBtn'),parallax:$('#parallaxInput')};
const scene={schemaVersion:'0.1.0',name:'storyworld_scene_01',canvas:{width:1600,height:2000,aspectRatio:'4:5'},objects:[]};
let selectedId=null;
let drag=null;
let pointer={x:800,y:1000};
const defaults={background:.08,architecture:.28,furniture:.55,decor:.72,foreground:.92,character:.62};
function uid(name){return `${name.toLowerCase().replace(/[^a-z0-9]+/g,'_')}_${Date.now().toString(36)}`}
function active(){return scene.objects.find(object=>object.id===selectedId)}
function canvasPoint(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*(canvas.width/rect.width),y:(event.clientY-rect.top)*(canvas.height/rect.height)}}
function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})}
async function createObject({name,src,category='decor',assetId=null}){const image=await loadImage(src);const scale=Math.min(1,canvas.width*.62/image.width);const object={id:uid(name),assetId,name,category,src,anchor:'center',position:{x:canvas.width/2,y:canvas.height/2},scale,rotation:0,depth:defaults[category]??.5,opacity:1,blur:category==='background'?8:0,locked:false,visible:true,image};scene.objects.push(object);selectedId=object.id;render()}
function drawObject(object){if(!object.visible||!object.image)return;const parallax=ui.parallax.checked?(object.depth-.5)*72:0;const px=(pointer.x/canvas.width-.5)*parallax;const py=(pointer.y/canvas.height-.5)*parallax;ctx.save();ctx.globalAlpha=object.opacity;ctx.filter=object.blur?`blur(${object.blur}px)`:'none';ctx.translate(object.position.x+px,object.position.y+py);ctx.rotate(object.rotation*Math.PI/180);ctx.scale(object.scale,object.scale);ctx.drawImage(object.image,-object.image.width/2,-object.image.height/2);ctx.restore();if(object.id===selectedId){const width=object.image.width*object.scale;const height=object.image.height*object.scale;ctx.save();ctx.translate(object.position.x+px,object.position.y+py);ctx.rotate(object.rotation*Math.PI/180);ctx.strokeStyle='#514638';ctx.lineWidth=4;ctx.setLineDash([14,10]);ctx.strokeRect(-width/2,-height/2,width,height);ctx.restore()}}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f5eee3';ctx.fillRect(0,0,canvas.width,canvas.height);scene.objects.forEach(drawObject);renderLayerList();syncInspector()}
function renderLayerList(){ui.list.innerHTML='';[...scene.objects].reverse().forEach(object=>{const li=document.createElement('li');const button=document.createElement('button');button.type='button';button.className=object.id===selectedId?'active':'';button.textContent=`${object.visible?'👁':'□'} ${object.name} · ${object.category}`;button.onclick=()=>{selectedId=object.id;render()};li.append(button);ui.list.append(li)})}
function syncInspector(){const object=active();[ui.name,ui.category,ui.scale,ui.rotation,ui.opacity,ui.blur,ui.depth,ui.visible,ui.locked].forEach(input=>input.disabled=!object);if(!object){ui.name.value='';return}ui.name.value=object.name;ui.category.value=object.category;ui.scale.value=object.scale;ui.rotation.value=object.rotation;ui.opacity.value=object.opacity;ui.blur.value=object.blur;ui.depth.value=object.depth;ui.visible.checked=object.visible;ui.locked.checked=object.locked}
function updateObject(patch){const object=active();if(!object)return;Object.assign(object,patch);render()}
function hitTest(point){for(let i=scene.objects.length-1;i>=0;i--){const object=scene.objects[i];if(object.locked||!object.visible)continue;const width=object.image.width*object.scale;const height=object.image.height*object.scale;if(point.x>=object.position.x-width/2&&point.x<=object.position.x+width/2&&point.y>=object.position.y-height/2&&point.y<=object.position.y+height/2)return object}return null}
function reorder(target){const index=scene.objects.findIndex(object=>object.id===selectedId);if(index<0)return;const [object]=scene.objects.splice(index,1);target==='front'?scene.objects.push(object):scene.objects.unshift(object);render()}
function removeObject(){scene.objects=scene.objects.filter(object=>object.id!==selectedId);selectedId=scene.objects.at(-1)?.id??null;render()}
function exportScene(){const exportable={...scene,objects:scene.objects.map(({image,...object})=>object)};download(`${scene.name}.json`,'application/json',JSON.stringify(exportable,null,2))}
function exportPng(){const previous=selectedId;selectedId=null;render();canvas.toBlob(blob=>{selectedId=previous;render();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${scene.name}.png`;anchor.click();URL.revokeObjectURL(url)},'image/png')}
function exportPrompt(){const items=scene.objects.filter(object=>object.visible).map(object=>`${object.category}: ${object.name}, depth ${object.depth.toFixed(2)}, blur ${object.blur}`).join('\n');const prompt=`Flow scene reference. 4:5 vertical composition. Layered scene graph:\n${items}\nUse soft matte rendering, warm muted palette, low contrast, readable composition and subtle parallax depth.`;download(`${scene.name}_prompt.txt`,'text/plain',prompt)}
function download(name,type,content){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
function demoSvg(label,fill,width,height){return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" rx="48" fill="${fill}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="80" fill="#4b443a">${label}</text></svg>`)}
function createDemo(){createObject({name:'blurred exterior',category:'background',src:demoSvg('Exterior','#c8d3bd',1700,2100)});createObject({name:'wall with window',category:'architecture',src:demoSvg('Wall + window','#eadfce',1500,1200)});createObject({name:'green sofa',category:'furniture',src:demoSvg('Sofa','#9aaa85',900,420)});createObject({name:'warm rug',category:'decor',src:demoSvg('Rug','#c78f72',850,300)});createObject({name:'foreground plant',category:'foreground',src:demoSvg('Plant','#7e8f6d',360,720)})}
ui.file.onchange=event=>{[...event.target.files].forEach(file=>createObject({name:file.name.replace(/\.[^.]+$/,''),src:URL.createObjectURL(file),category:'decor'}));event.target.value=''};
ui.demo.onclick=createDemo;ui.clear.onclick=()=>{scene.objects=[];selectedId=null;render()};
ui.name.oninput=event=>updateObject({name:event.target.value});ui.category.onchange=event=>updateObject({category:event.target.value,depth:defaults[event.target.value]??.5});ui.scale.oninput=event=>updateObject({scale:+event.target.value});ui.rotation.oninput=event=>updateObject({rotation:+event.target.value});ui.opacity.oninput=event=>updateObject({opacity:+event.target.value});ui.blur.oninput=event=>updateObject({blur:+event.target.value});ui.depth.oninput=event=>updateObject({depth:+event.target.value});ui.visible.onchange=event=>updateObject({visible:event.target.checked});ui.locked.onchange=event=>updateObject({locked:event.target.checked});
ui.back.onclick=()=>reorder('back');ui.front.onclick=()=>reorder('front');ui.delete.onclick=removeObject;ui.png.onclick=exportPng;ui.json.onclick=exportScene;ui.prompt.onclick=exportPrompt;ui.parallax.onchange=render;
canvas.onpointerdown=event=>{const point=canvasPoint(event);const object=hitTest(point);if(!object){selectedId=null;render();return}selectedId=object.id;drag={id:object.id,offsetX:point.x-object.position.x,offsetY:point.y-object.position.y};canvas.setPointerCapture(event.pointerId);render()};
canvas.onpointermove=event=>{pointer=canvasPoint(event);if(drag){const object=scene.objects.find(item=>item.id===drag.id);if(object){object.position.x=pointer.x-drag.offsetX;object.position.y=pointer.y-drag.offsetY}}if(drag||ui.parallax.checked)render()};
canvas.onpointerup=event=>{drag=null;canvas.releasePointerCapture(event.pointerId)};
render();
