const canvas=document.querySelector('#canvas');
const ctx=canvas.getContext('2d');
const $=selector=>document.querySelector(selector);
const ui={file:$('#fileInput'),demo:$('#demoBtn'),clear:$('#clearBtn'),list:$('#layerList'),name:$('#nameInput'),category:$('#categoryInput'),scale:$('#scaleInput'),rotation:$('#rotationInput'),opacity:$('#opacityInput'),blur:$('#blurInput'),depth:$('#depthInput'),visible:$('#visibleInput'),locked:$('#lockedInput'),back:$('#backBtn'),front:$('#frontBtn'),delete:$('#deleteBtn'),png:$('#pngBtn'),json:$('#jsonBtn'),prompt:$('#promptBtn'),cameraX:$('#cameraXInput'),cameraY:$('#cameraYInput'),perspective:$('#perspectiveInput'),zoom:$('#zoomInput'),tilt:$('#tiltInput'),resetCamera:$('#resetCameraBtn'),autoOrbit:$('#autoOrbitBtn'),cameraStatus:$('#cameraStatus')};
const scene={schemaVersion:'0.2.0',name:'storyworld_scene_01',canvas:{width:1920,height:1080,aspectRatio:'16:9'},camera:{x:0,y:0,perspective:1,zoom:1,tilt:0,autoOrbit:false},objects:[]};
let selectedId=null;
let drag=null;
let orbitFrame=null;
const defaults={background:.08,architecture:.28,furniture:.55,decor:.72,foreground:.92,character:.62};
const supportsCanvasFilter=typeof ctx.filter==='string';
function uid(name){return `${name.toLowerCase().replace(/[^a-z0-9]+/g,'_')}_${Date.now().toString(36)}`}
function active(){return scene.objects.find(object=>object.id===selectedId)}
function canvasPoint(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*(canvas.width/rect.width),y:(event.clientY-rect.top)*(canvas.height/rect.height)}}
function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})}
async function createObject({name,src,category='decor',assetId=null}){const image=await loadImage(src);const scale=Math.min(1,canvas.width*.45/image.width);const object={id:uid(name),assetId,name,category,src,anchor:'center',position:{x:canvas.width/2,y:canvas.height/2},scale,rotation:0,depth:defaults[category]??.5,opacity:1,blur:category==='background'?8:0,locked:false,visible:true,image};scene.objects.push(object);selectedId=object.id;render()}
function cameraOffset(object){const z=object.depth-.5;return{x:-scene.camera.x*z*260*scene.camera.perspective,y:-scene.camera.y*z*150*scene.camera.perspective}}
function drawImageOnly(object){ctx.drawImage(object.image,-object.image.width/2,-object.image.height/2)}
function drawBlurFallback(object){const b=Math.max(0,object.blur);if(!b){drawImageOnly(object);return}const steps=Math.min(12,Math.max(4,Math.round(b)));ctx.globalAlpha=(object.opacity||1)/(steps+1);drawImageOnly(object);for(let i=1;i<=steps;i++){const r=b*i*.9;const a=i*2.399963;ctx.drawImage(object.image,-object.image.width/2+Math.cos(a)*r,-object.image.height/2+Math.sin(a)*r);ctx.drawImage(object.image,-object.image.width/2-Math.cos(a)*r,-object.image.height/2-Math.sin(a)*r)}}
function drawObject(object){if(!object.visible||!object.image)return;const offset=cameraOffset(object);const scale=object.scale*scene.camera.zoom*(1+(object.depth-.5)*0.18*scene.camera.perspective);ctx.save();ctx.globalAlpha=object.opacity;ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(scene.camera.tilt*Math.PI/180);ctx.translate(object.position.x-canvas.width/2+offset.x,object.position.y-canvas.height/2+offset.y);ctx.rotate(object.rotation*Math.PI/180);ctx.scale(scale,scale);if(object.blur>0&&supportsCanvasFilter){ctx.filter=`blur(${object.blur}px)`;drawImageOnly(object);ctx.filter='none'}else{drawBlurFallback(object)}ctx.restore();if(object.id===selectedId){const width=object.image.width*scale;const height=object.image.height*scale;ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(scene.camera.tilt*Math.PI/180);ctx.translate(object.position.x-canvas.width/2+offset.x,object.position.y-canvas.height/2+offset.y);ctx.rotate(object.rotation*Math.PI/180);ctx.strokeStyle='#514638';ctx.lineWidth=4;ctx.setLineDash([14,10]);ctx.strokeRect(-width/2,-height/2,width,height);ctx.restore()}}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f5eee3';ctx.fillRect(0,0,canvas.width,canvas.height);scene.objects.forEach(drawObject);renderLayerList();syncInspector();syncCamera()}
function renderLayerList(){ui.list.innerHTML='';[...scene.objects].reverse().forEach(object=>{const li=document.createElement('li');const button=document.createElement('button');button.type='button';button.className=object.id===selectedId?'active':'';button.textContent=`${object.visible?'👁':'□'} ${object.name} · ${object.category}`;button.onclick=()=>{selectedId=object.id;render()};li.append(button);ui.list.append(li)})}
function syncInspector(){const object=active();[ui.name,ui.category,ui.scale,ui.rotation,ui.opacity,ui.blur,ui.depth,ui.visible,ui.locked].forEach(input=>input.disabled=!object);if(!object){ui.name.value='';return}ui.name.value=object.name;ui.category.value=object.category;ui.scale.value=object.scale;ui.rotation.value=object.rotation;ui.opacity.value=object.opacity;ui.blur.value=object.blur;ui.depth.value=object.depth;ui.visible.checked=object.visible;ui.locked.checked=object.locked}
function syncCamera(){ui.cameraX.value=scene.camera.x;ui.cameraY.value=scene.camera.y;ui.perspective.value=scene.camera.perspective;ui.zoom.value=scene.camera.zoom;ui.tilt.value=scene.camera.tilt;ui.autoOrbit.textContent=scene.camera.autoOrbit?'Stop orbit':'Auto orbit';ui.cameraStatus.textContent=`Camera ${scene.camera.x.toFixed(2)}, ${scene.camera.y.toFixed(2)} · Perspective ${scene.camera.perspective.toFixed(2)} · Zoom ${scene.camera.zoom.toFixed(2)}`}
function updateObject(patch){const object=active();if(!object)return;Object.assign(object,patch);render()}
function updateCamera(patch){Object.assign(scene.camera,patch);render()}
function hitTest(point){for(let i=scene.objects.length-1;i>=0;i--){const object=scene.objects[i];if(object.locked||!object.visible)continue;const offset=cameraOffset(object);const scale=object.scale*scene.camera.zoom*(1+(object.depth-.5)*0.18*scene.camera.perspective);const width=object.image.width*scale;const height=object.image.height*scale;const x=object.position.x+offset.x;const y=object.position.y+offset.y;if(point.x>=x-width/2&&point.x<=x+width/2&&point.y>=y-height/2&&point.y<=y+height/2)return object}return null}
function reorder(target){const index=scene.objects.findIndex(object=>object.id===selectedId);if(index<0)return;const [object]=scene.objects.splice(index,1);target==='front'?scene.objects.push(object):scene.objects.unshift(object);render()}
function removeObject(){scene.objects=scene.objects.filter(object=>object.id!==selectedId);selectedId=scene.objects.at(-1)?.id??null;render()}
function exportScene(){const exportable={...scene,objects:scene.objects.map(({image,...object})=>object)};download(`${scene.name}.json`,'application/json',JSON.stringify(exportable,null,2))}
function exportPng(){const previous=selectedId;selectedId=null;render();canvas.toBlob(blob=>{selectedId=previous;render();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${scene.name}.png`;anchor.click();URL.revokeObjectURL(url)},'image/png')}
function exportPrompt(){const items=scene.objects.filter(object=>object.visible).map(object=>`${object.category}: ${object.name}, depth ${object.depth.toFixed(2)}, blur ${object.blur}`).join('\n');const prompt=`Flow scene reference. 16:9 wide composition. Layered scene graph:\n${items}\nCamera: x ${scene.camera.x}, y ${scene.camera.y}, perspective ${scene.camera.perspective}, zoom ${scene.camera.zoom}, tilt ${scene.camera.tilt}. Use soft matte rendering, warm muted palette, low contrast, readable composition and subtle parallax depth.`;download(`${scene.name}_prompt.txt`,'text/plain',prompt)}
function download(name,type,content){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
function demoSvg(label,fill,width,height){return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" rx="48" fill="${fill}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="80" fill="#4b443a">${label}</text></svg>`)}
function createDemo(){scene.objects=[];createObject({name:'blurred exterior',category:'background',src:demoSvg('Exterior','#c8d3bd',2100,1180)});createObject({name:'wall with window',category:'architecture',src:demoSvg('Wall + window','#eadfce',1800,900)});createObject({name:'green sofa',category:'furniture',src:demoSvg('Sofa','#9aaa85',900,340)});createObject({name:'warm rug',category:'decor',src:demoSvg('Rug','#c78f72',760,220)});createObject({name:'foreground plant',category:'foreground',src:demoSvg('Plant','#7e8f6d',300,620)})}
function orbit(){if(!scene.camera.autoOrbit)return;const t=Date.now()/900;scene.camera.x=Math.sin(t);scene.camera.y=Math.sin(t*.7)*.35;render();orbitFrame=requestAnimationFrame(orbit)}
function toggleOrbit(){scene.camera.autoOrbit=!scene.camera.autoOrbit;if(scene.camera.autoOrbit){orbit()}else{cancelAnimationFrame(orbitFrame);render()}}
ui.file.onchange=event=>{[...event.target.files].forEach(file=>createObject({name:file.name.replace(/\.[^.]+$/,''),src:URL.createObjectURL(file),category:'decor'}));event.target.value=''};
ui.demo.onclick=createDemo;ui.clear.onclick=()=>{scene.objects=[];selectedId=null;render()};
ui.name.oninput=event=>updateObject({name:event.target.value});ui.category.onchange=event=>updateObject({category:event.target.value,depth:defaults[event.target.value]??.5});ui.scale.oninput=event=>updateObject({scale:+event.target.value});ui.rotation.oninput=event=>updateObject({rotation:+event.target.value});ui.opacity.oninput=event=>updateObject({opacity:+event.target.value});ui.blur.oninput=event=>updateObject({blur:+event.target.value});ui.depth.oninput=event=>updateObject({depth:+event.target.value});ui.visible.onchange=event=>updateObject({visible:event.target.checked});ui.locked.onchange=event=>updateObject({locked:event.target.checked});
ui.cameraX.oninput=event=>updateCamera({x:+event.target.value});ui.cameraY.oninput=event=>updateCamera({y:+event.target.value});ui.perspective.oninput=event=>updateCamera({perspective:+event.target.value});ui.zoom.oninput=event=>updateCamera({zoom:+event.target.value});ui.tilt.oninput=event=>updateCamera({tilt:+event.target.value});ui.resetCamera.onclick=()=>{scene.camera.x=0;scene.camera.y=0;scene.camera.perspective=1;scene.camera.zoom=1;scene.camera.tilt=0;scene.camera.autoOrbit=false;cancelAnimationFrame(orbitFrame);render()};ui.autoOrbit.onclick=toggleOrbit;
ui.back.onclick=()=>reorder('back');ui.front.onclick=()=>reorder('front');ui.delete.onclick=removeObject;ui.png.onclick=exportPng;ui.json.onclick=exportScene;ui.prompt.onclick=exportPrompt;
canvas.onpointerdown=event=>{const point=canvasPoint(event);const object=hitTest(point);if(!object){selectedId=null;render();return}selectedId=object.id;drag={id:object.id,offsetX:point.x-object.position.x,offsetY:point.y-object.position.y};canvas.setPointerCapture(event.pointerId);render()};
canvas.onpointermove=event=>{if(drag){const point=canvasPoint(event);const object=scene.objects.find(item=>item.id===drag.id);if(object){object.position.x=point.x-drag.offsetX;object.position.y=point.y-drag.offsetY;render()}}};
canvas.onpointerup=event=>{drag=null;canvas.releasePointerCapture(event.pointerId)};
render();
