const canvas=document.querySelector('#sceneCanvas');
const ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s);
const ui={fileInput:$('#fileInput'),addDemoBtn:$('#addDemoBtn'),clearBtn:$('#clearBtn'),layerList:$('#layerList'),nameInput:$('#nameInput'),typeInput:$('#typeInput'),scaleInput:$('#scaleInput'),rotationInput:$('#rotationInput'),opacityInput:$('#opacityInput'),blurInput:$('#blurInput'),depthInput:$('#depthInput'),sendBackBtn:$('#sendBackBtn'),bringFrontBtn:$('#bringFrontBtn'),deleteBtn:$('#deleteBtn'),exportPngBtn:$('#exportPngBtn'),exportJsonBtn:$('#exportJsonBtn'),parallaxToggle:$('#parallaxToggle')};
const scene={name:'storyworld_scene',canvas:{width:1600,height:2000,aspectRatio:'4:5'},layers:[]};
let selectedId=null,drag=null,pointer={x:800,y:1000};
function id(name){return `${name.replace(/\W+/g,'_').toLowerCase()}_${Date.now().toString(36)}`}
function depth(type){return {background:.08,architecture:.28,furniture:.55,decor:.72,foreground:.92}[type]??.5}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}}
function selected(){return scene.layers.find(l=>l.id===selectedId)}
function load(src){return new Promise((ok,fail)=>{const img=new Image();img.onload=()=>ok(img);img.onerror=fail;img.src=src})}
async function addLayer(name,src,type='decor'){const image=await load(src);const scale=Math.min(1,canvas.width*.62/image.width);const layer={id:id(name),assetId:null,name,type,src,x:canvas.width/2,y:canvas.height/2,scale,rotation:0,opacity:1,blur:type==='background'?8:0,depth:depth(type),image};scene.layers.push(layer);selectedId=layer.id;render()}
function draw(layer){if(!layer.image)return;const move=ui.parallaxToggle.checked?(layer.depth-.5)*72:0;const ox=(pointer.x/canvas.width-.5)*move;const oy=(pointer.y/canvas.height-.5)*move;ctx.save();ctx.globalAlpha=layer.opacity;ctx.filter=layer.blur?`blur(${layer.blur}px)`:'none';ctx.translate(layer.x+ox,layer.y+oy);ctx.rotate(layer.rotation*Math.PI/180);ctx.scale(layer.scale,layer.scale);ctx.drawImage(layer.image,-layer.image.width/2,-layer.image.height/2);ctx.restore();if(layer.id===selectedId){const w=layer.image.width*layer.scale,h=layer.image.height*layer.scale;ctx.save();ctx.translate(layer.x+ox,layer.y+oy);ctx.rotate(layer.rotation*Math.PI/180);ctx.strokeStyle='#514638';ctx.lineWidth=4;ctx.setLineDash([14,10]);ctx.strokeRect(-w/2,-h/2,w,h);ctx.restore()}}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f9f2e7';ctx.fillRect(0,0,canvas.width,canvas.height);scene.layers.forEach(draw);renderList();sync()}
function renderList(){ui.layerList.innerHTML='';[...scene.layers].reverse().forEach(layer=>{const li=document.createElement('li');const b=document.createElement('button');b.type='button';b.className=layer.id===selectedId?'active':'';b.textContent=`${layer.name} · ${layer.type}`;b.onclick=()=>{selectedId=layer.id;render()};li.append(b);ui.layerList.append(li)})}
function sync(){const l=selected();[ui.nameInput,ui.typeInput,ui.scaleInput,ui.rotationInput,ui.opacityInput,ui.blurInput,ui.depthInput].forEach(i=>i.disabled=!l);if(!l){ui.nameInput.value='';return}ui.nameInput.value=l.name;ui.typeInput.value=l.type;ui.scaleInput.value=l.scale;ui.rotationInput.value=l.rotation;ui.opacityInput.value=l.opacity;ui.blurInput.value=l.blur;ui.depthInput.value=l.depth}
function patch(data){const l=selected();if(!l)return;Object.assign(l,data);render()}
function hit(p){for(let i=scene.layers.length-1;i>=0;i--){const l=scene.layers[i],w=l.image.width*l.scale,h=l.image.height*l.scale;if(p.x>=l.x-w/2&&p.x<=l.x+w/2&&p.y>=l.y-h/2&&p.y<=l.y+h/2)return l}return null}
function order(where){const i=scene.layers.findIndex(l=>l.id===selectedId);if(i<0)return;const [l]=scene.layers.splice(i,1);where==='front'?scene.layers.push(l):scene.layers.unshift(l);render()}
function remove(){scene.layers=scene.layers.filter(l=>l.id!==selectedId);selectedId=scene.layers.at(-1)?.id??null;render()}
function saveJson(){const data={...scene,layers:scene.layers.map(({image,...l})=>l)};download(`${scene.name}.json`,'application/json',JSON.stringify(data,null,2))}
function savePng(){const old=selectedId;selectedId=null;render();canvas.toBlob(blob=>{selectedId=old;render();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${scene.name}.png`;a.click();URL.revokeObjectURL(url)},'image/png')}
function download(name,type,content){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function demoSvg(label,fill,w,h){return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" rx="48" fill="${fill}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="80" fill="#4b443a">${label}</text></svg>`)}
function demo(){addLayer('Blurred exterior',demoSvg('Exterior','#c8d3bd',1700,2100),'background');addLayer('Back wall with window',demoSvg('Wall + window','#eadfce',1500,1200),'architecture');addLayer('Sofa',demoSvg('Sofa','#9aaa85',900,420),'furniture');addLayer('Rug',demoSvg('Rug','#c78f72',850,300),'decor');addLayer('Foreground plant',demoSvg('Plant','#7e8f6d',360,720),'foreground')}
ui.fileInput.onchange=e=>{[...e.target.files].forEach(file=>addLayer(file.name.replace(/\.[^.]+$/,''),URL.createObjectURL(file),'decor'));e.target.value=''};
ui.addDemoBtn.onclick=demo;ui.clearBtn.onclick=()=>{scene.layers=[];selectedId=null;render()};
ui.nameInput.oninput=e=>patch({name:e.target.value});ui.typeInput.onchange=e=>patch({type:e.target.value,depth:depth(e.target.value)});ui.scaleInput.oninput=e=>patch({scale:+e.target.value});ui.rotationInput.oninput=e=>patch({rotation:+e.target.value});ui.opacityInput.oninput=e=>patch({opacity:+e.target.value});ui.blurInput.oninput=e=>patch({blur:+e.target.value});ui.depthInput.oninput=e=>patch({depth:+e.target.value});
ui.sendBackBtn.onclick=()=>order('back');ui.bringFrontBtn.onclick=()=>order('front');ui.deleteBtn.onclick=remove;ui.exportJsonBtn.onclick=saveJson;ui.exportPngBtn.onclick=savePng;ui.parallaxToggle.onchange=render;
canvas.onpointerdown=e=>{const p=point(e),l=hit(p);if(!l){selectedId=null;render();return}selectedId=l.id;drag={id:l.id,ox:p.x-l.x,oy:p.y-l.y};canvas.setPointerCapture(e.pointerId);render()};
canvas.onpointermove=e=>{pointer=point(e);if(drag){const l=scene.layers.find(x=>x.id===drag.id);if(l){l.x=pointer.x-drag.ox;l.y=pointer.y-drag.oy}}if(drag||ui.parallaxToggle.checked)render()};
canvas.onpointerup=e=>{drag=null;canvas.releasePointerCapture(e.pointerId)};
render();
