import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

const $ = s => document.querySelector(s);
const app = $('#app'), viewport = $('#viewport'), modeBtn = $('#modeBtn'), seedBtn = $('#seedBtn'), resetBtn = $('#resetBtn'), hideUiBtn = $('#hideUiBtn'), helpBtn = $('#helpBtn'), brushLockBtn = $('#brushLockBtn'), timeSlider = $('#timeSlider'), densitySelect = $('#densitySelect'), undoBtn = $('#undoBtn'), redoBtn = $('#redoBtn'), saveBtn = $('#saveBtn'), loadBtn = $('#loadBtn'), loadFileInput = $('#loadFileInput');
const tools = [...document.querySelectorAll('.tool[data-tool]')], sizeButtons = [...document.querySelectorAll('.size-btn')];
const WORLD = 62, SEG = 118, WATER = -0.18, STORE = 'storyworlds.autosave.v090', MAX_HISTORY = 70;

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(42, innerWidth / innerHeight, 0.1, 240); camera.position.set(19, 16, 25);
const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; viewport.innerHTML = ''; viewport.appendChild(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); Object.assign(controls, { enableDamping: true, dampingFactor: .08, minDistance: 8, maxDistance: 90, maxPolarAngle: Math.PI * .55, enablePan: false }); controls.target.set(0, 0, 0);
const hemi = new THREE.HemisphereLight(0xffffff, 0x7b806f, 1.25), sun = new THREE.DirectionalLight(0xffffff, 2.4); sun.position.set(18, 24, 10); sun.castShadow = true; scene.add(hemi, sun);
const sky = new THREE.Mesh(new THREE.SphereGeometry(160, 32, 16), new THREE.MeshBasicMaterial({ color: 0xdce8e2, side: THREE.BackSide })); scene.add(sky);
const sunDisk = new THREE.Mesh(new THREE.SphereGeometry(1.1, 20, 12), new THREE.MeshBasicMaterial({ color: 0xffe8a0, depthTest: false }));
const moonDisk = new THREE.Mesh(new THREE.SphereGeometry(.8, 20, 12), new THREE.MeshBasicMaterial({ color: 0xe8edff, depthTest: false })); sunDisk.renderOrder = moonDisk.renderOrder = 999; scene.add(sunDisk, moonDisk);
const cloudMat = new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: .42, depthWrite: false }), clouds = new THREE.Group(); scene.add(clouds);
function addCloud(x, y, z, s) { const g = new THREE.Group(); for (let i = 0; i < 5; i++) { const p = new THREE.Mesh(new THREE.SphereGeometry(s * (.45 + i * .05), 10, 6), cloudMat); p.scale.set(2.25, .32, .62); p.position.set(i * s * .42, Math.sin(i) * .06, Math.cos(i) * .11); g.add(p); } g.position.set(x, y, z); g.rotation.y = x * .05; clouds.add(g); }
[-26, -7, 14, 28].forEach((x, i) => addCloud(x, 14 + i % 2 * 1.5, -22 + i * 13, 1.25 + i % 2 * .35));

const world = new THREE.Group(); scene.add(world);
const geom = new THREE.PlaneGeometry(WORLD, WORLD, SEG, SEG); geom.rotateX(-Math.PI / 2);
const pos = geom.attributes.position, colors = [], data = [];
for (let i = 0; i < pos.count; i++) { data[i] = { h: 0, water: 0, veg: 0, forest: 0, stone: 0, terrace: 0, path: 0 }; colors.push(.67, .72, .55); }
geom.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
const terrain = new THREE.Mesh(geom, new THREE.MeshStandardMaterial({ vertexColors: true, roughness: .96 })); terrain.receiveShadow = true; world.add(terrain);
const water = new THREE.Mesh(new THREE.PlaneGeometry(WORLD, WORLD, 48, 48).rotateX(-Math.PI / 2), new THREE.MeshStandardMaterial({ color: 0x8cbaba, transparent: true, opacity: .17, roughness: .35 })); water.position.y = WATER; world.add(water);
const generatedPlants = new THREE.Group(), generatedTrees = new THREE.Group(), generatedRocks = new THREE.Group(), paintedPlants = new THREE.Group(), paintedTrees = new THREE.Group(), paintedRocks = new THREE.Group(), paintedPaths = new THREE.Group(), paintedBridges = new THREE.Group(), paintedHouses = new THREE.Group(); world.add(generatedPlants, generatedTrees, generatedRocks, paintedPlants, paintedTrees, paintedRocks, paintedPaths, paintedBridges, paintedHouses);
const mat = c => new THREE.MeshStandardMaterial({ color: c, roughness: .95 });
const mats = { grass: mat(0x61784f), grass2: mat(0x7f9365), flower1: mat(0xe8cad6), flower2: mat(0xf0df9a), flower3: mat(0xd6d1ef), trunk: mat(0x765d42), leaf: mat(0x728a5e), leaf2: mat(0x58734f), pine: mat(0x51694a), palm: mat(0x6f8d58), rock: mat(0x9f988a), path: mat(0xb99b6d), bridge: mat(0x826648), wall: mat(0xd9c5a3), wall2: mat(0xcbb28f), roof: mat(0x8e5845), roof2: mat(0xa46a4e), door: mat(0x554232), white: mat(0xf1e8d4) };
Object.values(mats).forEach(m => { m.roughness = .92; });

let seed = Date.now() % 999999, currentTool = 'grass', mode = 'explore', brushLock = false, brushRadius = 2.6, pointerDown = null, currentDensity = 'normal', timeOfDay = .28;
let paintedPlantRecords = [], paintedTreeRecords = [], paintedRockRecords = [], paintedPathRecords = [], paintedBridgeRecords = [], paintedHouseRecords = []; const undoStack = [], redoStack = [];
const raycaster = new THREE.Raycaster(), pointer = new THREE.Vector2(), plane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 0), brushMat = new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: .38, side: THREE.DoubleSide }); let brush = makeBrush(); scene.add(brush);

function rand(x, z, s = seed) { const n = Math.sin((x + s * .011) * 12.9898 + (z - s * .017) * 78.233) * 43758.5453; return n - Math.floor(n); }
function fbm(x, z) { return (rand(x, z) - .5) + (rand(x * 1.9 + 11, z * 1.9 - 7) - .5) * .34 + (rand(x * 3.4 - 4, z * 3.4 + 9) - .5) * .12; }
function gauss(x, z, cx, cz, r, h) { return Math.exp(-(((x - cx) ** 2 + (z - cz) ** 2) / (r * r))) * h; }
function smoothstep(a, b, x) { const t = THREE.MathUtils.clamp((x - a) / (b - a), 0, 1); return t * t * (3 - 2 * t); }
function visibleHeight(d) { return d.h - d.water * .2 + d.stone * .12; }
function nearestIndex(x, z) { let best = 0, dist = Infinity; for (let i = 0; i < pos.count; i += 1) { const dd = (pos.getX(i) - x) ** 2 + (pos.getZ(i) - z) ** 2; if (dd < dist) { dist = dd; best = i; } } return best; }
function heightAt(x, z) { return pos.getY(nearestIndex(x, z)); }
function dataAt(x, z) { return data[nearestIndex(x, z)]; }
function biomeAt(x, z) { const h = heightAt(x, z), d = dataAt(x, z); if (d.water > .14 || Math.abs(h - WATER) < .5) return 'coast'; if (h > 1.1) return 'highland'; if (d.forest > .45) return 'forest'; return 'plains'; }
function nearWater(x, z, r = 1.15) { for (let a = 0; a < 8; a++) if (dataAt(x + Math.cos(a * Math.PI / 4) * r, z + Math.sin(a * Math.PI / 4) * r).water > .18) return true; return false; }
function colorAt(i) { const d = data[i], h = visibleHeight(d), near = THREE.MathUtils.clamp(1 - Math.abs(h - WATER) / .72, 0, 1), beach = near * (1 - d.water * .8); const c = new THREE.Color(0xa8b589).lerp(new THREE.Color(0x74885d), d.veg * .14 + d.forest * .12).lerp(new THREE.Color(0xd5c795), beach * .85).lerp(new THREE.Color(0x8cbaba), d.water * .8).lerp(new THREE.Color(0xb69a6d), d.path * .72).lerp(new THREE.Color(0x9d9488), d.stone * .45).lerp(new THREE.Color(0x927c66), Math.max(0, d.h - 1.1) * .08); geom.attributes.color.setXYZ(i, c.r, c.g, c.b); }
function applyPoint(i) { pos.setY(i, visibleHeight(data[i])); colorAt(i); }
function applyAllTerrain() { for (let i = 0; i < pos.count; i++) applyPoint(i); updateTerrain(); }
function updateTerrain() { pos.needsUpdate = true; geom.attributes.color.needsUpdate = true; geom.computeVertexNormals(); }
function clearGroup(g) { for (const c of [...g.children]) { g.remove(c); if (c.children) clearGroup(c); if (c.geometry) c.geometry.dispose(); } }
function clearGenerated() { clearGroup(generatedPlants); clearGroup(generatedTrees); clearGroup(generatedRocks); }
function clearPainted() { [paintedPlants, paintedTrees, paintedRocks, paintedPaths, paintedBridges, paintedHouses].forEach(clearGroup); }

function makeRiver(x, z, offset = 0) { const v = Math.sin((z + seed * .002 + offset) * .11) * 7 + Math.sin((z + offset) * .23) * 2.8; return Math.abs(x - v); }
function generateSeed(newSeed = Math.floor(Math.random() * 999999), record = true) { if (record) pushHistory(); seed = newSeed; clearGenerated(); clearPainted(); paintedPlantRecords = []; paintedTreeRecords = []; paintedRockRecords = []; paintedPathRecords = []; paintedBridgeRecords = []; paintedHouseRecords = []; const coast = rand(2, 3) > .55, ridgeX = (rand(4, 5) - .5) * 18, ridgeZ = (rand(7, 8) - .5) * 18; for (let i = 0; i < pos.count; i++) { const x = pos.getX(i), z = pos.getZ(i); const n = fbm(x * .07, z * .07); let h = n * .18 + gauss(x, z, ridgeX, ridgeZ, 13, 1.2) + gauss(x, z, -ridgeZ * .55, ridgeX * .35, 9, .8); const river = makeRiver(x, z); const rmask = 1 - smoothstep(.36, 1.15, river + n * .15); const l1 = gauss(x, z, (rand(20, 21) - .5) * 26, (rand(21, 22) - .5) * 26, 5.8, 1); const l2 = rand(5, 6) > .55 ? gauss(x, z, (rand(30, 31) - .5) * 30, (rand(31, 32) - .5) * 30, 4.5, 1) : 0; let waterMask = Math.max(rmask * .72, l1, l2); if (coast) waterMask = Math.max(waterMask, smoothstep(21, 28, Math.hypot(x + 8, z - 6))); h -= waterMask * .42; const bank = 1 - smoothstep(.9, 3.6, river); const forest = THREE.MathUtils.clamp(gauss(x, z, -10, 8, 13, .65) + bank * .28 + (rand(x * .18, z * .18) > .72 ? .22 : 0), 0, 1); const veg = THREE.MathUtils.clamp(.28 + rand(x * .24, z * .24) * .32 + bank * .18 + forest * .18, 0, 1); const stone = THREE.MathUtils.clamp(Math.max(0, h - .9) * .22 + rand(x * 1.6, z * 1.6) * .04, 0, .8); data[i] = { h, water: THREE.MathUtils.clamp(waterMask, 0, 1), veg, forest, stone, terrace: 0, path: 0 }; } for (let i = 0; i < pos.count; i++) applyPoint(i); updateTerrain(); refreshDecorations(); resetCamera(); autoSave(); updateStatus('Nuevo seed'); }

function addClusterLeaf(g, x, y, z, s, material) { const c = new THREE.Mesh(new THREE.DodecahedronGeometry(s, 1), material); c.position.set(x, y, z); c.scale.set(1.05 + rand(x, z) * .3, .9, 1.05); g.add(c); return c; }
function addGrass(x, z, scale = 1, group = generatedPlants) { const g = new THREE.Group(); const blades = 2 + Math.floor(rand(x, z) * 4); for (let i = 0; i < blades; i++) { const blade = new THREE.Mesh(new THREE.ConeGeometry(.025 * scale, .18 * scale, 4), rand(x + i, z) > .5 ? mats.grass : mats.grass2); blade.position.set((rand(x + i, z) - .5) * .55, .08 * scale, (rand(x, z + i) - .5) * .55); blade.rotation.z = (rand(x + i, z + 2) - .5) * .35; g.add(blade); } if (rand(x + 8, z - 4) > .46) { const f = new THREE.Mesh(new THREE.SphereGeometry(.035 * scale, 6, 4), [mats.flower1, mats.flower2, mats.flower3][Math.floor(rand(x, z) * 3)]); f.position.set((rand(x + 2, z) - .5) * .4, .14 * scale, (rand(x, z + 2) - .5) * .4); g.add(f); } g.position.set(x, heightAt(x, z) + .012, z); group.add(g); }
function addTree(x, z, scale = 1, group = generatedTrees) { const biome = biomeAt(x, z), g = new THREE.Group(); const trunkH = biome === 'coast' ? .62 : biome === 'highland' ? .52 : .58; const trunk = new THREE.Mesh(new THREE.CylinderGeometry(.045 * scale, .08 * scale, trunkH * scale, 7), mats.trunk); trunk.position.y = trunkH * scale * .5; g.add(trunk); if (biome === 'coast') { for (let i = 0; i < 6; i++) { const leaf = new THREE.Mesh(new THREE.ConeGeometry(.12 * scale, .56 * scale, 5), mats.palm); leaf.position.y = .76 * scale; leaf.rotation.z = Math.PI / 2.55; leaf.rotation.y = i * Math.PI / 3; g.add(leaf); } } else if (biome === 'highland' || rand(x, z) > .58) { const p1 = new THREE.Mesh(new THREE.ConeGeometry(.34 * scale, .72 * scale, 7), mats.pine), p2 = new THREE.Mesh(new THREE.ConeGeometry(.25 * scale, .55 * scale, 7), mats.pine); p1.position.y = .68 * scale; p2.position.y = .96 * scale; g.add(p1, p2); } else { addClusterLeaf(g, 0, .76 * scale, 0, .32 * scale, rand(x, z) > .5 ? mats.leaf : mats.leaf2); addClusterLeaf(g, -.19 * scale, .68 * scale, .08 * scale, .22 * scale, mats.leaf); addClusterLeaf(g, .2 * scale, .7 * scale, -.06 * scale, .22 * scale, mats.leaf2); } g.position.set(x, heightAt(x, z) + .02, z); g.rotation.y = rand(x, z) * Math.PI * 2; group.add(g); }
function addRock(x, z, scale = 1, group = generatedRocks) { const g = new THREE.Group(); const pieces = 1 + Math.floor(rand(x, z) * 3); for (let i = 0; i < pieces; i++) { const r = new THREE.Mesh(new THREE.DodecahedronGeometry(.15 * scale * (1 - i * .12), 1), mats.rock); r.position.set((rand(x + i, z) - .5) * .45, .06 * scale, (rand(x, z + i) - .5) * .35); r.scale.set(1.15, .45 + rand(z, x) * .18, .8); r.rotation.set(rand(x, z) * .5, rand(x + 1, z) * Math.PI * 2, rand(x, z + 1) * .5); g.add(r); } g.position.set(x, heightAt(x, z) + .03, z); group.add(g); }
function addPathTile(x, z, scale = 1, group = paintedPaths) { const g = new THREE.Group(); const p = new THREE.Mesh(new THREE.CircleGeometry(.28 * scale, 14), mats.path); p.rotation.x = -Math.PI / 2; p.scale.set(1.65, .68, 1); p.rotation.z = rand(x, z) * Math.PI; g.add(p); if (rand(x, z + 2) > .62) addRockToGroup(g, .42 * scale, .02, .16 * scale); g.position.set(x, heightAt(x, z) + .024, z); group.add(g); }
function addRockToGroup(g, x, z, s) { const r = new THREE.Mesh(new THREE.DodecahedronGeometry(s, 1), mats.rock); r.scale.y = .45; r.position.set(x, .06, z); g.add(r); }
function addBridge(x, z, scale = 1, group = paintedBridges) { const g = new THREE.Group(); const deck = new THREE.Mesh(new THREE.BoxGeometry(2.35 * scale, .13 * scale, .78 * scale), mats.bridge); deck.position.y = .14 * scale; g.add(deck); for (let i = -2; i <= 2; i++) { const plank = new THREE.Mesh(new THREE.BoxGeometry(.34 * scale, .16 * scale, .92 * scale), mats.bridge); plank.position.set(i * .42 * scale, .2 * scale, 0); plank.rotation.y = (rand(x + i, z) - .5) * .08; g.add(plank); } for (const side of [-1, 1]) for (const px of [-.95, 0, .95]) { const post = new THREE.Mesh(new THREE.CylinderGeometry(.045 * scale, .052 * scale, .48 * scale, 6), mats.bridge); post.position.set(px * scale, .38 * scale, side * .44 * scale); g.add(post); } g.position.set(x, Math.max(heightAt(x, z), WATER) + .08, z); g.rotation.y = rand(x, z) * Math.PI; group.add(g); }
function addHouse(x, z, scale = 1, group = paintedHouses) { const g = new THREE.Group(); const base = new THREE.Mesh(new THREE.BoxGeometry(1.28 * scale, .78 * scale, 1.05 * scale), mats.wall); base.position.y = .48 * scale; const side = new THREE.Mesh(new THREE.BoxGeometry(.48 * scale, .56 * scale, .9 * scale), mats.wall2); side.position.set(.74 * scale, .36 * scale, -.04 * scale); const roof = new THREE.Mesh(new THREE.ConeGeometry(.96 * scale, .55 * scale, 4), mats.roof); roof.position.y = 1.05 * scale; roof.rotation.y = Math.PI / 4; roof.scale.set(1.15, 1, .95); const roof2 = new THREE.Mesh(new THREE.ConeGeometry(.48 * scale, .35 * scale, 4), mats.roof2); roof2.position.set(.74 * scale, .74 * scale, -.04 * scale); roof2.rotation.y = Math.PI / 4; const door = new THREE.Mesh(new THREE.BoxGeometry(.22 * scale, .38 * scale, .035 * scale), mats.door); door.position.set(-.25 * scale, .28 * scale, .54 * scale); const win = new THREE.Mesh(new THREE.BoxGeometry(.18 * scale, .16 * scale, .035 * scale), mats.white); win.position.set(.27 * scale, .5 * scale, .54 * scale); g.add(base, side, roof, roof2, door, win); for (let i = 0; i < 5; i++) addGrassToGroup(g, (rand(x + i, z) - .5) * 1.8 * scale, (rand(x, z + i) - .5) * 1.5 * scale, .55 * scale); g.position.set(x, heightAt(x, z) + .025, z); g.rotation.y = Math.round(rand(x, z) * 3) * Math.PI / 2; group.add(g); }
function addGrassToGroup(g, x, z, scale) { const blade = new THREE.Mesh(new THREE.ConeGeometry(.025 * scale, .15 * scale, 4), mats.grass); blade.position.set(x, .09 * scale, z); blade.rotation.z = (rand(x, z) - .5) * .35; g.add(blade); }
function refreshDecorations() { clearGenerated(); const mult = currentDensity === 'low' ? .45 : currentDensity === 'high' ? 1.35 : .86, step = 2.2; for (let gx = -WORLD / 2 + 1; gx < WORLD / 2 - 1; gx += step) for (let gz = -WORLD / 2 + 1; gz < WORLD / 2 - 1; gz += step) { const x = gx + (rand(gx * .73, gz * .41) - .5) * step * 1.45, z = gz + (rand(gx * .37 + 9, gz * .81 - 4) - .5) * step * 1.45; if (Math.abs(x) > WORLD * .48 || Math.abs(z) > WORLD * .48) continue; const d = dataAt(x, z), h = heightAt(x, z); if (d.water > .22 || d.path > .25) continue; const n = rand(x * 1.91 + 7, z * 1.37 - 3); if (d.veg > .18 && n > 1 - .35 * mult) addGrass(x, z, .65 + rand(x, z + 2) * .28); if (d.forest > .38 && n > 1 - .11 * mult) addTree(x, z, .72 + rand(x + 3, z) * .55); if ((d.stone > .66 || h > 1.65 || biomeAt(x, z) === 'coast') && rand(x + 9, z - 4) > 1 - .035 * mult) addRock(x, z, .2 + rand(x, z) * .25); } }
function rebuildPaintedObjects() { clearPainted(); paintedPlantRecords.forEach(o => addGrass(o.x, o.z, o.s, paintedPlants)); paintedTreeRecords.forEach(o => addTree(o.x, o.z, o.s, paintedTrees)); paintedRockRecords.forEach(o => addRock(o.x, o.z, o.s, paintedRocks)); paintedPathRecords.forEach(o => addPathTile(o.x, o.z, o.s, paintedPaths)); paintedBridgeRecords.forEach(o => addBridge(o.x, o.z, o.s, paintedBridges)); paintedHouseRecords.forEach(o => addHouse(o.x, o.z, o.s, paintedHouses)); }
function hasBridgeNear(x, z) { return paintedBridgeRecords.some(o => Math.hypot(o.x - x, o.z - z) < 2.1); }
function scatterObjects(p, type) { const amount = type === 'grass' ? 8 : type === 'forest' ? 3 : type === 'path' ? 5 : type === 'stone' ? 2 : 1; for (let k = 0; k < amount; k++) { const a = rand(p.x + k * 7, p.z - k) * Math.PI * 2, r = Math.sqrt(rand(p.x - k, p.z + k)) * brushRadius * (type === 'path' ? .46 : .82), x = p.x + Math.cos(a) * r, z = p.z + Math.sin(a) * r, d = dataAt(x, z); if (d.water > .22 && !['bridge', 'path'].includes(type)) continue; if (type === 'grass') { const o = { x, z, s: .58 + rand(x, z) * .32 }; paintedPlantRecords.push(o); addGrass(o.x, o.z, o.s, paintedPlants); } if (type === 'forest') { const o = { x, z, s: .72 + rand(x, z) * .42 }; paintedTreeRecords.push(o); addTree(o.x, o.z, o.s, paintedTrees); } if (type === 'stone') { const o = { x, z, s: .18 + rand(x, z) * .28 }; paintedRockRecords.push(o); addRock(o.x, o.z, o.s, paintedRocks); } if (type === 'path') { const o = { x, z, s: .72 + rand(x, z) * .16 }; paintedPathRecords.push(o); addPathTile(o.x, o.z, o.s, paintedPaths); if (nearWater(x, z, 1.05) && !hasBridgeNear(x, z)) { const b = { x, z, s: .92 }; paintedBridgeRecords.push(b); addBridge(b.x, b.z, b.s, paintedBridges); } } } if (type === 'bridge') { const o = { x: p.x, z: p.z, s: 1 }; paintedBridgeRecords.push(o); addBridge(o.x, o.z, o.s, paintedBridges); } if (type === 'house') { if (dataAt(p.x, p.z).water > .16) return; const o = { x: p.x, z: p.z, s: .9 + rand(p.x, p.z) * .14 }; paintedHouseRecords.push(o); addHouse(o.x, o.z, o.s, paintedHouses); } }
function eraseNear(p) { const keep = o => Math.hypot(o.x - p.x, o.z - p.z) > brushRadius; paintedPlantRecords = paintedPlantRecords.filter(keep); paintedTreeRecords = paintedTreeRecords.filter(keep); paintedRockRecords = paintedRockRecords.filter(keep); paintedPathRecords = paintedPathRecords.filter(keep); paintedBridgeRecords = paintedBridgeRecords.filter(keep); paintedHouseRecords = paintedHouseRecords.filter(keep); rebuildPaintedObjects(); }
function paintAt(p) { const target = heightAt(p.x, p.z), pathRadius = brushRadius * .4; for (let i = 0; i < pos.count; i++) { const dist = Math.hypot(pos.getX(i) - p.x, pos.getZ(i) - p.z), limit = currentTool === 'path' ? pathRadius : brushRadius; if (dist > limit) continue; const f = Math.pow(1 - dist / limit, 2.2), d = data[i]; if (currentTool === 'grass') { d.veg = THREE.MathUtils.clamp(d.veg + f * .52, 0, 1); d.forest = Math.max(0, d.forest - f * .14); } else if (currentTool === 'forest') { d.forest = THREE.MathUtils.clamp(d.forest + f * .42, 0, 1); d.veg = THREE.MathUtils.clamp(d.veg + f * .12, 0, 1); } else if (currentTool === 'water') { d.water = THREE.MathUtils.clamp(d.water + f * .14, 0, 1); d.h -= f * .018; } else if (currentTool === 'stone') d.stone = THREE.MathUtils.clamp(d.stone + f * .18, 0, 1); else if (currentTool === 'path') { d.path = THREE.MathUtils.clamp(d.path + f * .42, 0, 1); d.veg = Math.max(0, d.veg - f * .38); d.forest = Math.max(0, d.forest - f * .22); } else if (currentTool === 'raise') { d.h = THREE.MathUtils.clamp(d.h + f * .36, -2, 4.8); d.water = Math.max(0, d.water - f * .18); } else if (currentTool === 'lower') { d.h = THREE.MathUtils.clamp(d.h - f * .3, -2.4, 4.8); } else if (currentTool === 'erase') { d.path = Math.max(0, d.path - f * .6); d.veg = Math.max(0, d.veg - f * .45); d.forest = Math.max(0, d.forest - f * .35); d.stone = Math.max(0, d.stone - f * .2); } else if (currentTool === 'smooth') d.h = THREE.MathUtils.lerp(d.h, target, f * .12); else if (currentTool === 'flatten') d.h = THREE.MathUtils.lerp(d.h, target, f * .34); applyPoint(i); } if (currentTool === 'grass') scatterObjects(p, 'grass'); if (currentTool === 'forest') scatterObjects(p, 'forest'); if (currentTool === 'stone') scatterObjects(p, 'stone'); if (currentTool === 'path') scatterObjects(p, 'path'); if (currentTool === 'bridge') scatterObjects(p, 'bridge'); if (currentTool === 'house') scatterObjects(p, 'house'); if (currentTool === 'erase') eraseNear(p); updateTerrain(); clearTimeout(window._decoTimer); window._decoTimer = setTimeout(refreshDecorations, 420); }

function snapshot() { return JSON.stringify({ version: '0.9.0', seed, timeOfDay, currentDensity, data, paintedPlantRecords, paintedTreeRecords, paintedRockRecords, paintedPathRecords, paintedBridgeRecords, paintedHouseRecords }); }
function restoreFromString(str) { const s = JSON.parse(str); if (!s || !Array.isArray(s.data) || s.data.length !== data.length) throw new Error('Archivo incompatible'); seed = s.seed ?? seed; timeOfDay = s.timeOfDay ?? timeOfDay; currentDensity = s.currentDensity ?? currentDensity; for (let i = 0; i < data.length; i++) data[i] = { h: 0, water: 0, veg: 0, forest: 0, stone: 0, terrace: 0, path: 0, ...s.data[i] }; paintedPlantRecords = s.paintedPlantRecords || []; paintedTreeRecords = s.paintedTreeRecords || []; paintedRockRecords = s.paintedRockRecords || []; paintedPathRecords = s.paintedPathRecords || []; paintedBridgeRecords = s.paintedBridgeRecords || []; paintedHouseRecords = s.paintedHouseRecords || []; if (densitySelect) densitySelect.value = currentDensity; if (timeSlider) timeSlider.value = timeOfDay; applyAllTerrain(); refreshDecorations(); rebuildPaintedObjects(); updateSky(); autoSave(); updateStatus('Mundo cargado'); }
function pushHistory() { undoStack.push(snapshot()); if (undoStack.length > MAX_HISTORY) undoStack.shift(); redoStack.length = 0; updateUndoRedo(); }
function undo() { if (!undoStack.length) return; redoStack.push(snapshot()); restoreFromString(undoStack.pop()); updateUndoRedo(); updateStatus('Undo'); }
function redo() { if (!redoStack.length) return; undoStack.push(snapshot()); restoreFromString(redoStack.pop()); updateUndoRedo(); updateStatus('Redo'); }
function updateUndoRedo() { if (undoBtn) undoBtn.disabled = !undoStack.length; if (redoBtn) redoBtn.disabled = !redoStack.length; }
function autoSave() { try { localStorage.setItem(STORE, snapshot()); updateStatus('Autoguardado'); } catch {} }
function tryAutoLoad() { try { const saved = localStorage.getItem(STORE); if (saved) { restoreFromString(saved); updateStatus('Autoguardado cargado'); return true; } } catch {} return false; }
function downloadWorld() { const blob = new Blob([snapshot()], { type: 'application/json' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `storyworld-${seed}.storyworld`; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(a.href), 800); }
function uploadWorld(file) { const reader = new FileReader(); reader.onload = () => { pushHistory(); try { restoreFromString(String(reader.result)); } catch { alert('No pude cargar este mundo.'); } }; reader.readAsText(file); }
function updateStatus(msg) { const hint = $('#modeHint'); if (hint) hint.textContent = msg; }
function pointerPoint(e) { const r = renderer.domElement.getBoundingClientRect(); pointer.x = ((e.clientX - r.left) / r.width) * 2 - 1; pointer.y = -((e.clientY - r.top) / r.height) * 2 + 1; raycaster.setFromCamera(pointer, camera); const out = new THREE.Vector3(); raycaster.ray.intersectPlane(plane, out); return out; }
function makeBrush() { const b = new THREE.Mesh(new THREE.RingGeometry(brushRadius * .84, brushRadius, 64), brushMat); b.rotation.x = -Math.PI / 2; b.position.y = .12; b.visible = false; return b; }
function rebuildBrush() { scene.remove(brush); brush.geometry.dispose(); brush = makeBrush(); scene.add(brush); }
function setMode(next) { mode = next; app.dataset.mode = mode; modeBtn.textContent = mode === 'edit' ? 'Editar' : 'Explorar'; modeBtn.classList.toggle('primary', mode === 'explore'); controls.enabled = !(mode === 'edit' && brushLock); }
function setBrushLock(v) { brushLock = v; brushLockBtn.textContent = v ? 'Pincel: continuo' : 'Pincel: toque'; brushLockBtn.classList.toggle('is-active', v); controls.enabled = !(mode === 'edit' && brushLock); }
function updateSky() { const day = Math.max(0, Math.sin(timeOfDay * Math.PI)), skyColor = new THREE.Color(0x17213a).lerp(new THREE.Color(0xdce8e2), day); scene.background = skyColor; sky.material.color.copy(skyColor); hemi.intensity = .45 + day * 1.45; sun.intensity = .25 + day * 2.1; const angle = timeOfDay * Math.PI * 2 - Math.PI * .15; sun.position.set(Math.cos(angle) * 22, Math.sin(angle) * 22, 10); sunDisk.position.set(Math.cos(angle) * 48, Math.max(8, Math.sin(angle) * 30 + 18), -34); moonDisk.position.set(-Math.cos(angle) * 48, Math.max(8, -Math.sin(angle) * 30 + 18), -34); sunDisk.visible = day > .08; moonDisk.visible = day < .92; cloudMat.opacity = .16 + day * .38; water.material.color.copy(new THREE.Color(0x5a6b7d).lerp(new THREE.Color(0x8cbaba), day)); }
function resetCamera() { camera.position.set(19, 16, 25); controls.target.set(0, 0, 0); controls.update(); }
function stop(e) { e.preventDefault(); e.stopPropagation(); }
function bindButton(el, fn) { el?.addEventListener('pointerdown', stop); el?.addEventListener('pointerup', e => { stop(e); fn(); }); }

renderer.domElement.addEventListener('pointerdown', e => { pointerDown = { x: e.clientX, y: e.clientY, p: pointerPoint(e) }; brush.visible = mode === 'edit'; brush.position.set(pointerDown.p.x, .12, pointerDown.p.z); if (mode === 'edit') { pushHistory(); if (brushLock && currentTool !== 'house' && currentTool !== 'bridge') paintAt(pointerDown.p); } });
renderer.domElement.addEventListener('pointermove', e => { const p = pointerPoint(e); brush.visible = mode === 'edit'; brush.position.set(p.x, .12, p.z); if (mode === 'edit' && brushLock && pointerDown && currentTool !== 'house' && currentTool !== 'bridge') paintAt(p); });
renderer.domElement.addEventListener('pointerup', e => { if (!pointerDown) return; const moved = Math.hypot(e.clientX - pointerDown.x, e.clientY - pointerDown.y); if (mode === 'edit' && (currentTool === 'house' || currentTool === 'bridge' || (!brushLock && moved < 8))) paintAt(pointerDown.p); if (mode === 'edit') autoSave(); pointerDown = null; });
renderer.domElement.addEventListener('dblclick', resetCamera);
bindButton(modeBtn, () => setMode(mode === 'explore' ? 'edit' : 'explore')); bindButton(seedBtn, () => generateSeed()); bindButton(resetBtn, () => { pushHistory(); generateSeed(seed, false); }); bindButton(hideUiBtn, () => { app.classList.toggle('ui-hidden'); hideUiBtn.textContent = app.classList.contains('ui-hidden') ? '☰' : '👁️'; }); bindButton(helpBtn, () => $('#infoPanel')?.classList.toggle('is-hidden')); bindButton(brushLockBtn, () => setBrushLock(!brushLock)); bindButton(undoBtn, undo); bindButton(redoBtn, redo); bindButton(saveBtn, downloadWorld); bindButton(loadBtn, () => loadFileInput?.click()); loadFileInput?.addEventListener('change', e => { const file = e.target.files?.[0]; if (file) uploadWorld(file); e.target.value = ''; });
tools.forEach(btn => bindButton(btn, () => { currentTool = btn.dataset.tool; tools.forEach(b => b.classList.toggle('active', b === btn)); }));
sizeButtons.forEach(btn => bindButton(btn, () => { brushRadius = btn.dataset.size === 'small' ? 1.25 : btn.dataset.size === 'large' ? 4.8 : 2.6; sizeButtons.forEach(b => b.classList.toggle('active', b === btn)); rebuildBrush(); }));
densitySelect?.addEventListener('change', e => { pushHistory(); currentDensity = e.target.value; refreshDecorations(); autoSave(); }); timeSlider?.addEventListener('input', e => { timeOfDay = Number(e.target.value); updateSky(); autoSave(); });
addEventListener('resize', () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); });

generateSeed(seed, false); if (!tryAutoLoad()) autoSave(); setMode('explore'); setBrushLock(false); updateSky(); updateUndoRedo();
function animate() { controls.update(); const t = performance.now() * .001; water.position.y = WATER + Math.sin(t * 1.15) * .01; water.material.opacity = .16 + Math.sin(t * 1.3) * .014; clouds.children.forEach((c, i) => c.position.x += Math.sin(t + i) * .0008); renderer.render(scene, camera); requestAnimationFrame(animate); }
animate();
